version: "2"
services:
  facade:
    container_name: facade
    restart: always
    build: ./services/facade
    ports:
      - "9090:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USERNAME: storeuser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: gwdb
      A_SERVICE_HOST: a_service
      A_SERVICE_PORT: 5000
    links:
      - redis
      - mongo
      - mysql
      - a_service
    depends_on:
      - a_service
  a_service:
    container_name: a_service
    restart: always
    build: ./services/a-service
    ports:
      - "3000:5000"
    environment:
      REDIS_HOST: redis
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: storedb
      MYSQL_USERNAME: storeuser
      MYSQL_PASSWORD: password
    links:
      - redis
      - mongo
      - mysql
    depends_on:
      - redis
      - mongo
      - mysql
  redis:
    image: redis
    container_name: cache
    expose:
    - 6379
  mongo:
    container_name: mongo
    image: mvertes/alpine-mongo
    ports:
      - "33944:27017"
  mysql:
    build: ./database/docker/mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306
  db_migration:
    build: ./database/migrations
    restart: on-failure
    environment:
      NODE_ENV: dev
      MONGO_HOST: mongo
      MYSQL_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: admin
    command: ["npm", "run", "dbmigrate:all-up"]
    links:
      - mongo
      - mysql
    depends_on:
      - mongo
      - mysql
